---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[oud::default]
    attributes:
