---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  - name: centos-6.5

suites:
  - name: oud
    run_list:
    - recipe[oud::default]
